package com.attribes.incommon.util;

public class Constants {

    public static final String EXTRA_QBDIALOG = "qbdialog";
    public static final String EXTRA_QBUSERS = "qbUsers";
    public static String FLURRY_KEY = "BF3RF9TVFSN3YN643CHR";
	public static String IS_EDIT = "edit_mode";
	public static final String PROJECT_NUMBER = "136458693581";
	public static final int CHAT_NOTIFICATION_ID = 1;
	public static final int AUTO_PRESENCE_INTERVAL_IN_SECONDS = 30;
	public static final String PREFS_NAME = "registrationPreference";
	public static final String REGISTRATION_KEY = "registrationKey";
	public static final String USER_NAME = "userName";
	public static final String USER_AGE = "userAge";
	public static final String USER_PHOTO = "userPhoto";
	public static final String FACEBOOK_USER = "facebookUser";
	public static final String PERSON_DESCRIPTION = "personDescription";
	public static final String USER_INTERESTS = "userInterests";
	public static final String USER_ID_API = "userId";
	public static final String USER_SM_TOKEN = "sm_token";
	public static final String USER_IMAGE_URI= "userImageUri";
	public static final String PERSON_NAME = "userName";
	public static final String PERSON_AGE= "user_age";
	public static final String FACEBOOK_IMAGES ="facebookImages";
	public static final String PARSE_INSTALLATION_ID ="parseInstallationId";
	public static final String FACEBOOK_ALBUMS = "facebookAlbums";
	public static final String QB_USER_ID ="qBUserId";
	public static final String QB_USER_LOGIN = "qBUserLogin";
	public static final String QB_USER_PASSWORD = "qBUserPassword";
	public static final String FONT_PROXI_LIGHT = "Mark Simonson - Proxima Nova Light.ttf";
	public static final String FONT_PROXI_REGULAR = "Mark Simonson - Proxima Nova Regular.ttf";
	public static final String FONT_GINGER_REGULAR = "F37Ginger-Regular.ttf";
	public static final String FONT_AILERON_REGULAR= "Aileron-Regular.ttf";
	public static final String USER_FULL_NAME = "fullName" ;
	public static final int RC_SIGN_IN = 0;
	public static final CharSequence LOG_OUT_MESSAGE = "Are you sure you want to log out?";
	public static final String CONTACT_US_SUBJECT="InCommon Query";
	public static final String CONTACT_US_EMAIL="marketing@getincommon.com";
	public static final String CONTACT_US_DIALOG_TITLE = "Thank you!";
	public static final String CONTACT_US_DIALOG_MESSAGE = "We will respond you shortly";
	
	public static final int USER_STATUS_LOG_IN=1;
	public static final int USER_STATUS_LOG_OUT=0;
	public static final String PARAM_AUTHORIZATION = "authorization";
	public static final String PARAM_SM_TOKEN = "sm_token";
	public static final String PARAM_LATITUDE = "latitude";
	public static final String PARAM_LONGITUDE = "longitude";
	public static final String PARAM_DESCRIPTION="description";
	public static final String PARAM_IMAGE_URI="image_uri";
	public static final String PARAM_NAME="name";
	public static final String PARAM_AGE="age";
	public static final String PARAM_GENDER="gender";
	public static final String PARAM_INTERESTS="interests";
	
	public static final String PARAM_USER_STATUS="status";
	public static final String GENERAL_ERROR_MESSAGE = "Unable to work on your request this time";
	public static final String PARAM_USER_ID = "user_id";
	public static final String PARAM_PREFS_AGE="search_age";
	public static final String PARAM_PREFS_DISTANCE="search_distance";
	public static final String PARAM_PREFS_GENDER="search_gender";
	public static final String PARAM_PREFS_ALERTS="show_alerts";
	public static final String PARAM_PREFS_MATCHES="show_matches";
	public static final String PARAM_PREFS_MESSAGES="show_messages";
	public static final String AUTHORIZATION = "27AbcxXePB5fJPNUoluyx9byF61u";
	public static String BaseUrl ="http://178.62.105.140/index.php/api/v1";
	public static String SearchUser = "/users/search";
	public static String UserDetail = "/users/detail";
	public static String AllUsers = "/users/all";
	public static String FriendAdd = "/friends/add";
	public static String friendAccept= "/friends/accept";
	public static String friendAll ="/friends/all";
	public static String NOTIFICATIONSALL ="/notifications/all";
	public static String FRIEND_REJECT = "/friends/reject";
	public static String FRIEND_DELETE = "/friends/delete";
	public static String FRIEND_BLOCK= "/users/block";
	public static String FRIEND_LIKE = "/users/like";
	public static String FRIEND_REPORT ="/users/report";
	public static String MATCHES_ALL = "/matches/all";
	public static String CHAT_STATUS = "/users/chat_status";
	public static String USER_GET = "/users/get";
	public static String USER_STATUS = "/users/status";
	public static String USER_UPDATE = "/users/update";
	public static final String PROPERTY_APP_VERSION = "appVersion";
	public static final String PROPERTY_REG_ID = "registration_id";
	public static final String TAG = "PlayServicesHelper";
	public static final int PLAY_SERVICES_RESOLUTION_REQUEST = 9000;
    public static String EXTRA_CHAT_MODE = "mode";
    public static final String EXTRA_INTENT_GROUP = "groupName";
    public static enum Mode{PRIVATE , GROUP}

}
